version: '3.2'
services:
  test:
    build:
      context: .
      cache_from:
        - 'eu.gcr.io/symetics.com/audioslides-io:latest'
    environment:
      - MIX_ENV=test
      - DATABASE_MYSQL_HOSTNAME=db
      - DATABASE_MYSQL_PORT=3306
      - DATABASE_MYSQL_USERNAME=root
      - DATABASE_MYSQL_PASSWORD=""
      - BRANCH=$BRANCH
    depends_on:
      - db
    command: mix coveralls
  db:
    image: 'mysql:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=""
    ports:
      - "3306:3306"
